name: Release

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write
  issues: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  Required to avoid HEAD~1 errors

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Lint Last Commit Message
        run: |
          npx --yes @commitlint/cli@latest --config .commitlintrc.yml --from=HEAD~1 --to=HEAD

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
