name: Validate Commit Messages

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml
